package com.rohith.FitnessCutlet.api.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.rohith.FitnessCutlet.api.model.CalcResponse;
import com.rohith.FitnessCutlet.api.model.UserData;
import com.rohith.FitnessCutlet.service.Math;

@CrossOrigin
@RestController
public class CalcController {

    public String test;
    Math obj ;
    
    @Autowired
    public CalcController() {
        test = "\t *** This is generated by Rohith Chevvakula ***";
    }

    @RequestMapping(value = "/cal", method = RequestMethod.POST, consumes = "application/json")
    public CalcResponse calculate(@RequestBody UserData input) {
        obj = new Math(input);
        CalcResponse response = new CalcResponse();
        response.setAmoutOfCalories(obj.getDailyCalorieIntake());
        return response;
    }

    // @RequestMapping(value="/astrik")
    @RequestMapping(value="/astrik")
    public int test(@RequestParam int sxsrf, @RequestParam int b) {
        int a = 0;
        int response = a * b;
        return response;
    }

    // public static void main(String[] surbhi) {
    //     CalcController hdfiah = new CalcController();
    //     int result = hdfiah.test(1231234,5);

    //     System.out.println(result);
    // }
    
}