package com.rohith.FitnessCutlet.api.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import com.rohith.FitnessCutlet.api.model.CalcResponse;
import com.rohith.FitnessCutlet.api.model.UserData;
import com.rohith.FitnessCutlet.service.Math;

@CrossOrigin
@RestController
public class CalcController {

    public String authorTag;
    CalcResponse calcResponse;
    Math obj ;
    
    @Autowired
    public CalcController() {
        authorTag = "\t *** This is generated by Rohith Chevvakula ***";
        calcResponse = new CalcResponse();
    }

    @RequestMapping(value = "/cal", method = RequestMethod.POST, consumes = "application/json")
    public CalcResponse calculate(@RequestBody UserData input) {
        obj = new Math(input);
        calcResponse.setAmoutOfCalories(obj.getDailyCalorieIntake());
        return calcResponse;
    }
}